export const TYPES = {
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  LOAD_ACCOUNTS_SUCCESS: 'LOAD_ACCOUNTS_SUCCESS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
<<<<<<< 89fc953aab5363a0ba1a38a3d03ea61e86ad1800
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS'
=======
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT'
>>>>>>> bank: account delete functionality
}